trigger:
  - main
  
pr: none
  
variables: 
  # Service connection as configured in project settings
  prodConnection: ''

  # App name
  prodApp: 'website-prod'
  
stages:
  - stage: build
    displayName: 'Build'
    jobs:
    - job: build_test
      displayName: 'Build and test'
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'
      - script: |
          npm install
        displayName: 'npm install'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: '$(System.ArtifactsDirectory)'
  
  
  - stage: prod
    displayName: 'Prod'
    dependsOn: build
    jobs:
    - deployment: deployProd
      displayName: 'Deploy prod'
      environment: prod
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@1
              inputs:
                downloadPath: '$(System.DefaultWorkingDirectory)'
            - task: AzureWebApp@1
              inputs:
                azureSubscription: $(prodConnection)
                appType: 'webAppLinux'
                appName: $(prodApp)
                runtimeStack: 'NODE|12.1'
                startUpCommand: 'npm run start'
  